package com.xtu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTask<M extends BaseTask<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setDescribe(java.lang.String describe) {
		set("describe", describe);
	}

	public java.lang.String getDescribe() {
		return get("describe");
	}

	public void setExperience(java.lang.Integer experience) {
		set("experience", experience);
	}

	public java.lang.Integer getExperience() {
		return get("experience");
	}

	public void setEquipment(java.lang.Integer equipment) {
		set("equipment", equipment);
	}

	public java.lang.Integer getEquipment() {
		return get("equipment");
	}

	public void setMonsterid(java.lang.Integer monsterid) {
		set("monsterid", monsterid);
	}

	public java.lang.Integer getMonsterid() {
		return get("monsterid");
	}

	public void setMonsteramount(java.lang.Integer monsteramount) {
		set("monsteramount", monsteramount);
	}

	public java.lang.Integer getMonsteramount() {
		return get("monsteramount");
	}

	public void setMoney(java.lang.Integer money) {
		set("money", money);
	}

	public java.lang.Integer getMoney() {
		return get("money");
	}

	public void setMinimumrank(java.lang.Integer minimumrank) {
		set("minimumrank", minimumrank);
	}

	public java.lang.Integer getMinimumrank() {
		return get("minimumrank");
	}

}
