package com.xtu.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("account", "id", Account.class);
		arp.addMapping("arena", "rank", Arena.class);
		arp.addMapping("equipment", "id", Equipment.class);
		arp.addMapping("ladder", "id", Ladder.class);
		// Composite Primary Key order: floor,id
		arp.addMapping("ladder_monster", "floor,id", LadderMonster.class);
		arp.addMapping("monster", "id", Monster.class);
		arp.addMapping("person", "id", Person.class);
		// Composite Primary Key order: equipmentid,id
		arp.addMapping("person_equipment", "equipmentid,id", PersonEquipment.class);
		// Composite Primary Key order: id,taskid
		arp.addMapping("person_task", "id,taskid", PersonTask.class);
		arp.addMapping("task", "id", Task.class);
	}
}

