package com.xtu.common.model;

import com.xtu.common.model.base.BaseArena;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Arena extends BaseArena<Arena> {
	public static final Arena dao = new Arena().dao();
}
