package com.xtu.common.model;

import com.xtu.common.model.base.BaseEquipment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Equipment extends BaseEquipment<Equipment> {
	public static final Equipment dao = new Equipment().dao();
}
