package com.xtu.common.model;

import com.xtu.common.model.base.BaseLadder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ladder extends BaseLadder<Ladder> {
	public static final Ladder dao = new Ladder().dao();
}
