package com.xtu.common.model;

import com.xtu.common.model.base.BaseLadderMonster;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LadderMonster extends BaseLadderMonster<LadderMonster> {
	public static final LadderMonster dao = new LadderMonster().dao();
}
