package com.xtu.common.model;

import com.xtu.common.model.base.BaseMonster;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Monster extends BaseMonster<Monster> {
	public static final Monster dao = new Monster().dao();
}
