package com.xtu.common.model;

import com.xtu.common.model.base.BasePersonEquipment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonEquipment extends BasePersonEquipment<PersonEquipment> {
	public static final PersonEquipment dao = new PersonEquipment().dao();
}
