package com.xtu.common.model;

import com.xtu.common.model.base.BasePerson;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Person extends BasePerson<Person> {
	public static final Person dao = new Person().dao();
}
