package com.xtu.common.model;

import com.xtu.common.model.base.BasePersonTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonTask extends BasePersonTask<PersonTask> {
	public static final PersonTask dao = new PersonTask().dao();
}
